### ISSUE TITLE
hg38_RefSeq_Genes.bed and hg38_genome_CGI.bed file missing

### ISSUE THREAD

**Issue by AlbaEB** [cemordaunt/DMRfinder#2]
Hello, I launched this command:

Rscript --vanilla DMRfinder.R -n 1 -d <directory> -c 6 -e 14 -a hg38 -o CvsMD_chr1_DMR --mc.cores 10 --meanDiff_cutoff 0.08 <control names> <experimental names>

and I obtained:

[DMRfinder] Loading genes and CpG islands
Error in file(file, "rt") : cannot open the connection
Calls: read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/share/lasallelab/genomes/hg38/GTF/hg38_RefSeq_Genes.bed': No such file or directory
Execution halted

Where are hg38_RefSeq_Genes.bed and hg38_genome_CGI.bed files? How I can solve it?

Thank you!

**Comment by cemordaunt** [comment]
Hi @AlbaEB,

I've uploaded all of the gene and CpG island annotation files to DMRfinder/Annotations.

To use them, you'll need to edit DMRfinder.R under the 'Get gene and CpG island bed file names' section (line 499) to reflect their location on your system.

Best,
Charles
