### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by hmyh1202** [cemordaunt/DMRfinder#3]
Hello:

   Which R packages and tools should I install  ? 

The best !

**Comment by cemordaunt** [comment]
Hi,
To run DMRfinder, you’ll need the following R packages, along with any of their dependencies: optparse, BiocGenerics, Biobase, S4Vectors, matrixStats, DelayedArray, bsseq, DSS, permute, GenomicRanges, and scales.
Best,
Charles
